test PR code

diff --git a/.github/workflows/build-containers.yml b/.github/workflows/build-containers.yml
--- a/.github/workflows/build-containers.yml
+++ b/.github/workflows/build-containers.yml
@@ -2,193 +2,272 @@
 name: Build and push container images
 
 on:
-  push:
-  pull_request:
-  workflow_dispatch:
-  repository_dispatch:
-    types: [dispatch-build]
+ push:
+ pull_request:
+ workflow_dispatch:
+ repository_dispatch:
+   types: [dispatch-build]
 
 jobs:
-  make-date-tag:
-    runs-on: ubuntu-latest
-    outputs:
-      dtag: ${{ steps.mkdatetag.outputs.dtag }}
-    steps:
-      - name: make date tag
-        id: mkdatetag
-        run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT
+ make-date-tag:
+   runs-on: ubuntu-latest
+   outputs:
+     dtag: ${{ steps.mkdatetag.outputs.dtag }}
+   steps:
+     - name: make date tag
+       id: mkdatetag
+       run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT
 
-  build-image-list:
-    runs-on: ubuntu-latest
-    outputs:
-      images: ${{ steps.image-list.outputs.json }}
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+ build-image-list:
+   runs-on: ubuntu-latest
+   outputs:
+     matrix: ${{ steps.set_matrix.outputs.matrix }}
+   steps:
+     - uses: actions/checkout@v3
+       with:
+         fetch-depth: 0
 
-      - id: image-list
-        run: |
-          ORG_DIR=opensciencegrid
-          # Get the list of files changed based on the type of event
-          # kicking off the GHA:
-          # 1. For the main branch, diff the previous state of main vs
-          #    the current commit
-          # 2. For other branches (i.e., on someone's fork), diff main
-          #    vs the current commit
-          # 3. For PRs, diff the base ref vs the current commit
-          # 4. For everything else (e.g., dispatches), build all images
-          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]] ||
-             [[ $GITHUB_EVENT_NAME == 'push' ]]; then
-               if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
-                   BASE=$(git merge-base origin/$GITHUB_BASE_REF HEAD)
-               elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
-                   BASE=${{github.event.before}}
-               else
-                   BASE=origin/main
-               fi
-               # List image root dirs where files have changed and the
-               # root dir exists. Example value:
-               # "opensciencegrid/vo-frontend opensciencegrid/ospool-cm"
-               images=$(git diff --name-only \
-                                 "$BASE" \
-                                 "$GITHUB_SHA" |
-                        egrep "^$ORG_DIR/" |
-                        cut -d/ -f -2 |
-                        sort |
-                        uniq |
-                        xargs -I {} find . -type d \
-                                           -wholename ./{} \
-                                           -printf "%P\n")
-          else
-               # List all image root dirs. Example value:
-               # "opensciencegrid/vo-frontend opensciencegrid/ospool-cm"
-               images=$(find $ORG_DIR -mindepth 1 \
-                                      -maxdepth 1 \
-                                      -type d \
-                                      -printf "$ORG_DIR/%P\n")
-          fi
+     - id: image-list
+       run: |
+           ORG_DIR=opensciencegrid
+           if [[ $GITHUB_EVENT_NAME == 'pull_request' ]] ||
+              [[ $GITHUB_EVENT_NAME == 'push' ]]; then
+                if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+                    BASE=$(git merge-base origin/$GITHUB_BASE_REF HEAD)
+                elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
+                    BASE=${{github.event.before}}
+                else
+                    BASE=origin/main
+                fi
+                images=$(git diff --name-only \
+                                  "$BASE" \
+                                  "$GITHUB_SHA" |
+                         egrep "^$ORG_DIR/" |
+                         cut -d/ -f -2 |
+                         sort |
+                         uniq |
+                         xargs -I {} find . -type d \
+                                            -wholename ./{} \
+                                            -printf "%P\n")
+           else
+                images=$(find $ORG_DIR -mindepth 1 \
+                                       -maxdepth 1 \
+                                       -type d \
+                                       -printf "$ORG_DIR/%P\n")
+           fi
 
-          # Ensure that the generated JSON array has a member,
-          # otherwise GHA will throw an error about an empty matrix
-          # vector in subsequent steps
-          image_json=$(echo -n "${images:-dummy}" | jq -Rcs '.|split("\n")')
-          echo "json=$image_json" >> $GITHUB_OUTPUT
 
-  build:
-    runs-on: ubuntu-latest
-    needs: build-image-list
-    if: needs.build-image-list.outputs.images != '["dummy"]'
-    # Prevent a single build failure from killing the workflow.
-    # This is safe since subsequent pushes should fail on cache load
-    continue-on-error: true
-    strategy:
-      fail-fast: false
-      matrix:
-        image: ${{ fromJson(needs.build-image-list.outputs.images) }}
-        yum_repo: ['development', 'testing', 'release']
-        series:
-          - name: '3.6'
-            os: 'el7'
-          - name: '23'
-            os: 'el9'
-    steps:
-      - name: Build ${{ matrix.image }}:${{ matrix.series }}-${{ matrix.yum_repo }}
-        continue-on-error: ${{ matrix.yum_repo == 'development' }}
-        uses: opensciencegrid/build-container-action@v0.6.0
-        with:
-          osg_series: ${{ matrix.series.name }}
-          osg_repo: ${{ matrix.yum_repo }}
-          context: ${{ matrix.image }}
-          base_os: ${{ matrix.series.os }}
+           image_json=$(echo -n "${images:-dummy}" | jq -Rcs '.|split("\n") | map(select(. != ""))')
+           echo "$image_json" > image_list.json
+           echo "images=$(echo $images | tr '\n' ' ')" >> $GITHUB_OUTPUT
 
-  push:
-    runs-on: ubuntu-latest
-    if: >-
-      github.ref == 'refs/heads/main' &&
-      github.event_name != 'pull_request' &&
-      github.repository_owner == 'opensciencegrid' &&
-      needs.build-image-list.outputs.images != '["dummy"]'
-    needs: [make-date-tag, build-image-list, build]
-    strategy:
-      fail-fast: false
-      matrix:
-        image: ${{ fromJson(needs.build-image-list.outputs.images) }}
-        series:
-          - name: '3.6'
-            os: 'el7'
-          - name: '23'
-            os: 'el9'
-    steps:
-      - name: Push to Harbor (${{ matrix.series }}-development)
-        # FIXME: reenable for OSG 23 development when available
-        if: matrix.series.name != '23'
-        uses: opensciencegrid/push-container-action@main
-        with:
-          repo: development
-          osg_series: ${{ matrix.series.name }}
-          context: ${{ matrix.image }}
-          base_os: ${{ matrix.series.os }}
-          registry_url: hub.opensciencegrid.org
-          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
-          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
+     - name: Display image list
+       run: cat image_list.json
 
-      - name: Push to Harbor (${{ matrix.series.name }}-testing)
-        if: always()
-        uses: opensciencegrid/push-container-action@main
-        with:
-          repo: testing
-          osg_series: ${{ matrix.series.name }}
-          context: ${{ matrix.image }}
-          base_os: ${{ matrix.series.os }}
-          registry_url: hub.opensciencegrid.org
-          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
-          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
+     - name: Set up Python
+       uses: actions/setup-python@v2
+       with:
+         python-version: '3.x'
 
-      - name: Push to Harbor (${{ matrix.series.name }}-release)
-        if: always()
-        uses: opensciencegrid/push-container-action@main
-        with:
-          repo: release
-          osg_series: ${{ matrix.series.name }}
-          context: ${{ matrix.image }}
-          base_os: ${{ matrix.series.os }}
-          registry_url: hub.opensciencegrid.org
-          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
-          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
+     - name: Run build-job-matrix script
+       id: run-python-script
+       run: python scripts/build-job-matrix.py ${{ steps.image-list.outputs.images }}
 
-      - name: Push to Docker Hub (${{ matrix.series.name }}-development)
-        if: always()
-        uses: opensciencegrid/push-container-action@main
-        with:
-          repo: development
-          osg_series: ${{ matrix.series.name }}
-          context: ${{ matrix.image }}
-          base_os: ${{ matrix.series.os }}
-          registry_url: docker.io
-          registry_user: ${{ secrets.DOCKER_USERNAME }}
-          registry_pass: ${{ secrets.DOCKER_PASSWORD }}
+     - name: Read JSON and set as output
+       id: set_matrix
+       run: |
+         json_content=$(cat scripts/grouped_output.json)
+         echo "::set-output name=matrix::$(echo $json_content | jq -c '.include')"
 
-      - name: Push to Docker Hub (${{ matrix.series.name }}-testing)
-        if: always()
-        uses: opensciencegrid/push-container-action@main
-        with:
-          repo: testing
-          osg_series: ${{ matrix.series.name }}
-          context: ${{ matrix.image }}
-          base_os: ${{ matrix.series.os }}
-          registry_url: docker.io
-          registry_user: ${{ secrets.DOCKER_USERNAME }}
-          registry_pass: ${{ secrets.DOCKER_PASSWORD }}
+     - name: Verify scripts/output.json
+       run: |
+         echo "Content of scripts/grouped_output.json:"
+         cat scripts/grouped_output.json
 
-      - name: Push to Docker Hub (${{ matrix.series.name }}-release)
-        if: always()
-        uses: opensciencegrid/push-container-action@main
-        with:
-          repo: release
-          osg_series: ${{ matrix.series.name }}
-          context: ${{ matrix.image }}
-          base_os: ${{ matrix.series.os }}
-          registry_url: docker.io
-          registry_user: ${{ secrets.DOCKER_USERNAME }}
-          registry_pass: ${{ secrets.DOCKER_PASSWORD }}
+ build:
+   runs-on: ubuntu-latest
+   needs: build-image-list
+   strategy:
+     fail-fast: false
+     matrix:
+       include: ${{ fromJson(needs.build-image-list.outputs.matrix) }}
+   outputs:
+     matrix: ${{ toJson(matrix) }}
+   steps:
+     - uses: actions/checkout@v3
+
+     - name: Print raw matrix configuration
+       run: |
+         echo "Raw matrix configuration: ${{ matrix }}"
+
+     - name: Set up Python
+       uses: actions/setup-python@v2
+       with:
+         python-version: '3.x'
+
+     - name: Print and set configuration
+       run: |
+         echo "Building ${{ matrix.name }} with configuration ${{ matrix.config }}"
+         CONFIG="${{ matrix.config }}"
+         BASE_OS=$(echo $CONFIG | awk -F'-' '{print $1}')
+         OSG_SERIES=$(echo $CONFIG | awk -F'-' '{print $2}')
+         BASE_REPO=$(echo $CONFIG | awk -F'-' '{print $3}')
+         STANDARD_BUILD=$(echo $CONFIG | awk -F'-' '{print $4}')
+         REPO_BUILD=$(echo $CONFIG | awk -F'-' '{print $5}')
+         echo "BASE_OS: $BASE_OS"
+         echo "OSG_SERIES: $OSG_SERIES"
+         echo "BASE_REPO: $BASE_REPO"
+         echo "STANDARD_BUILD: $STANDARD_BUILD"
+         echo "REPO_BUILD: $REPO_BUILD"
+         echo "BASE_OS=$BASE_OS" >> $GITHUB_ENV
+         echo "OSG_SERIES=$OSG_SERIES" >> $GITHUB_ENV
+         echo "BASE_REPO=$BASE_REPO" >> $GITHUB_ENV
+         echo "STANDARD_BUILD=$STANDARD_BUILD" >> $GITHUB_ENV
+         echo "REPO_BUILD=$REPO_BUILD" >> $GITHUB_ENV
+
+     - name: Validate environment variables
+       run: |
+         echo "Validating environment variables:"
+         if [ -z "$BASE_OS" ] || [ -z "$OSG_SERIES" ] || [ -z "$BASE_REPO" ]; then
+           echo "Error: One or more environment variables are not set."
+           exit 1
+         else
+           echo "All required environment variables are set."
+         fi
+
+     - name: Build Image
+       run: |
+         DEFAULT_TAG=$(echo s3-backup-${OSG_SERIES}-${BASE_REPO}-${GITHUB_RUN_NUMBER} | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-')
+         docker build --build-arg BASE_OS=$BASE_OS \
+                      --build-arg BASE_OSG_SERIES=$OSG_SERIES \
+                      --build-arg BASE_REPO=$BASE_REPO \
+                      --tag $DEFAULT_TAG \
+                      --file opensciencegrid/${{ matrix.name }}/Dockerfile \
+                      opensciencegrid/${{ matrix.name }}
+
+ push:
+   runs-on: ubuntu-latest
+   needs: build
+   if: github.event_name != 'pull_request'
+   steps:
+     - uses: actions/checkout@v3
+
+     - name: Parse build matrix
+       id: parse-matrix
+       run: echo "matrix=$(echo '${{ needs.build.outputs.matrix }}' | jq -c '.include')" >> $GITHUB_OUTPUT
+
+     - name: Print parsed matrix
+       run:
+         |
+         echo "Parsed matrix: ${{ steps.parse-matrix.outputs.matrix }}"
+
+     - name: Print and set configuration
+       run: |
+         echo "Pushing ${{ steps.parse-matrix.outputs.matrix }}"
+         for CONFIG in $(echo '${{ steps.parse-matrix.outputs.matrix }}' | jq -r '.[] | @base64'); do
+           _jq() {
+             echo ${CONFIG} | base64 --decode | jq -r ${1}
+           }
+
+           BASE_OS=$(_jq '.base_os')
+           OSG_SERIES=$(_jq '.osg_series')
+           BASE_REPO=$(_jq '.base_repo')
+           STANDARD_BUILD=$(_jq '.standard_build')
+           REPO_BUILD=$(_jq '.repo_build')
+
+           echo "BASE_OS: $BASE_OS"
+           echo "OSG_SERIES: $OSG_SERIES"
+           echo "BASE_REPO: $BASE_REPO"
+           echo "STANDARD_BUILD: $STANDARD_BUILD"
+           echo "REPO_BUILD: $REPO_BUILD"
+           echo "BASE_OS=$BASE_OS" >> $GITHUB_ENV
+           echo "OSG_SERIES=$OSG_SERIES" >> $GITHUB_ENV
+           echo "BASE_REPO=$BASE_REPO" >> $GITHUB_ENV
+           echo "STANDARD_BUILD=$STANDARD_BUILD" >> $GITHUB_ENV
+           echo "REPO_BUILD=$REPO_BUILD" >> $GITHUB_ENV
+
+           # Ensure tags are formatted correctly
+           TAG=$(echo "${BASE_OS}-${OSG_SERIES}-${BASE_REPO}-${STANDARD_BUILD}-${REPO_BUILD}" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]._-')
+           TAG=$(echo "$TAG" | sed 's/--*/-/g' | sed 's/^[-]*//;s/[-]*$//')
+
+           echo "Pushing image with tag: $TAG"
+
+           # Push images to registries
+           docker tag $DEFAULT_TAG hub.opensciencegrid.org/ppathu/opensciencegrid:$TAG
+           docker push hub.opensciencegrid.org/ppathu/opensciencegrid:$TAG
+
+           docker tag $DEFAULT_TAG docker.io/ppathu/opensciencegrid:$TAG
+           docker push docker.io/ppathu/opensciencegrid:$TAG
+         done
+
+     - name: Push to Harbor (${{ matrix.osg_series }}-development)
+       if: matrix.osg_series != '23'
+       uses: opensciencegrid/push-container-action@main
+       with:
+         repo: development
+         osg_series: ${{ matrix.osg_series }}
+         context: opensciencegrid/${{ matrix.name }}
+         base_os: ${{ matrix.base_os }}
+         registry_url: hub.opensciencegrid.org
+         registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
+         registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
+
+     - name: Push to Harbor (${{ matrix.osg_series }}-testing)
+       if: always()
+       uses: opensciencegrid/push-container-action@main
+       with:
+         repo: testing
+         osg_series: ${{ matrix.osg_series }}
+         context: opensciencegrid/${{ matrix.name }}
+         base_os: ${{ matrix.base_os }}
+         registry_url: hub.opensciencegrid.org
+         registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
+         registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
+
+     - name: Push to Harbor (${{ matrix.osg_series }}-release)
+       if: always()
+       uses: opensciencegrid/push-container-action@main
+       with:
+         repo: release
+         osg_series: ${{ matrix.osg_series }}
+         context: opensciencegrid/${{ matrix.name }}
+         base_os: ${{ matrix.base_os }}
+         registry_url: hub.opensciencegrid.org
+         registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
+         registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
+
+     - name: Push to Docker Hub (${{ matrix.osg_series }}-development)
+       if: always()
+       uses: opensciencegrid/push-container-action@main
+       with:
+         repo: development
+         osg_series: ${{ matrix.osg_series }}
+         context: opensciencegrid/${{ matrix.name }}
+         base_os: ${{ matrix.base_os }}
+         registry_url: docker.io
+         registry_user: ${{ secrets.DOCKER_USERNAME }}
+         registry_pass: ${{ secrets.DOCKER_PASSWORD }}
+    
+     - name: Push to Docker Hub (${{ matrix.osg_series }}-testing)
+       if: always()
+       uses: opensciencegrid/push-container-action@main
+       with:
+         repo: testing
+         osg_series: ${{ matrix.osg_series }}
+         context: opensciencegrid/${{ matrix.name }}
+         base_os: ${{ matrix.base_os }}
+         registry_url: docker.io
+         registry_user: ${{ secrets.DOCKER_USERNAME }}
+         registry_pass: ${{ secrets.DOCKER_PASSWORD }}
+  
+     - name: Push to Docker Hub (${{ matrix.osg_series }}-release)
+       if: always()
+       uses: opensciencegrid/push-container-action@main
+       with:
+         repo: release
+         osg_series: ${{ matrix.osg_series }}
+         context: opensciencegrid/${{ matrix.name }}
+         base_os: ${{ matrix.base_os }}
+         registry_url: docker.io
+         registry_user: ${{ secrets.DOCKER_USERNAME }}
+         registry_pass: ${{ secrets.DOCKER_PASSWORD }}
